image: node:latest

pipelines:
  branches:
    master:
      - step:
          deployment: prod
          name: Deploy to production
          caches:
            - node
          script:
            - npm install
            - npm run build
            - scp -r ./$BUILD_DIR $USER@$HOST:$PUBLIC_PATH
    develop:
      - step:
          deployment: dev
          name: Deploy to development
          caches:
            - node
          script:
            - npm install
            - npm run build
            - scp -r ./$BUILD_DIR $USER@$HOST:$PUBLIC_PATH